### ISSUE TITLE
Verificar Versão do Python instalado na máquina ao iniciar o Harpia

### ISSUE THREAD

**Issue by ValneyFaria** [flschiavoni/harpia#125]
if sys.version_info < (2, 6):
    print("*** You need Python 2.6 or higher to use Harpia.")

**Comment by Exterminus** [comment]
O setup agora verifica a versão mínima python2.7.

**Comment by ValneyFaria** [comment]
Boa Gands


________________________________
De: Carlos Magno <notifications@github.com>
Enviado: sexta-feira, 28 de outubro de 2016 15:42
Para: flschiavoni/harpia
Cc: ValneyFaria; Author
Assunto: Re: [flschiavoni/harpia] Verificar Versão do Python instalado na máquina ao iniciar o Harpia (#125)


O setup agora verifica a versão mínima python2.7.

-
